/**
 * Inbox requests — the schema'd ask (spec /05). Canonical state lives in the
 * ledger; inbox/R-*.md cards are rendered mirrors. For credential/setup
 * kinds, the STEPS are template-generated by the core from structured fields
 * (model prose is confined to a labeled context block and never contributes
 * URLs) — a card can't social-engineer what it can't write.
 */
import path from "node:path";
import type { Store } from "./store.js";
import type { InboxKind } from "./schema.js";
import type { FileOp } from "./store.js";
import type { CfEvent } from "./events.js";

export interface InboxPayload {
  what: string;
  why: string; // traceable: → hypothesis → metric
  steps: string[]; // core-generated for credential/setup kinds
  blocking: string;
  context?: string; // model prose, clearly labeled in renders
  choices?: Array<{ key: string; label: string; detail?: string }>;
  hypothesis?: string;
  metric?: string;
  content?: string;
  channel?: string;
}

export function renderCardMarkdown(id: number, kind: InboxKind, p: InboxPayload, urgent: boolean, createdAt: string): string {
  const lines: string[] = [];
  lines.push("---");
  lines.push(`id: R-${id}`);
  lines.push(`kind: ${kind}`);
  lines.push(`urgent: ${urgent}`);
  lines.push(`created_at: "${createdAt}"`);
  lines.push(`state: open`);
  lines.push("---");
  lines.push("");
  lines.push(`# ${urgent ? "🚨 " : ""}R-${id} · ${kind}`);
  lines.push("");
  lines.push(`**What:** ${p.what}`);
  lines.push("");
  lines.push(`**Why:** ${p.why}`);
  lines.push("");
  if (p.steps.length > 0) {
    lines.push(`**Exact steps:**`);
    p.steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
    lines.push("");
  }
  if (p.choices && p.choices.length > 0) {
    lines.push(`**Choices:**`);
    for (const c of p.choices) {
      lines.push(`- \`${c.key}\` — ${c.label}${c.detail ? ` (${c.detail})` : ""}`);
    }
    lines.push("");
  }
  lines.push(`**Blocking:** ${p.blocking}`);
  lines.push("");
  if (p.context) {
    lines.push(`**Context (written by an agent — verify before trusting):**`);
    lines.push("");
    lines.push(p.context);
    lines.push("");
  }
  lines.push("---");
  const resolve =
    kind === "approve_hypothesis"
      ? `cronfounder resolve R-${id} --approve            # fund the recommended bet\ncronfounder resolve R-${id} --choice <H-id>     # fund a different one\ncronfounder resolve R-${id} --reject --reason "..."`
      : kind === "approve_content"
        ? `cronfounder resolve R-${id} --approve\ncronfounder resolve R-${id} --reject --reason "..."`
        : kind === "decide"
          ? `cronfounder resolve R-${id} --choice <key>`
          : `cronfounder resolve R-${id} --done              # after completing the steps above`;
  lines.push("```");
  lines.push(resolve);
  lines.push("```");
  lines.push("");
  return lines.join("\n");
}

/** Create an inbox request: event + rendered card mirror. Returns the R-id. */
export async function fileRequest(
  store: Store,
  actor: string,
  kind: InboxKind,
  payload: InboxPayload,
  opts: { blockingKind?: string; blockingId?: string; urgent?: boolean } = {},
): Promise<number> {
  const id = store.nextId("inbox");
  const createdAt = new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
  const events: CfEvent[] = [
    store.event(actor, "inbox_created", {
      request: id,
      kind,
      payload,
      blocking_kind: opts.blockingKind ?? null,
      blocking_id: opts.blockingId ?? null,
      urgent: opts.urgent ?? false,
    }),
  ];
  const fileOps: FileOp[] = [
    {
      kind: "write",
      file: path.join(store.company.paths.inbox, `R-${id}.md`),
      contents: renderCardMarkdown(id, kind, payload, opts.urgent ?? false, createdAt),
    },
  ];
  await store.commit(events, fileOps, [`${actor} filed inbox request R-${id} (${kind}): ${payload.what}`]);
  return id;
}

export function credentialSteps(envVar: string, purpose: string): string[] {
  return [
    `create/locate the credential for: ${purpose}`,
    `export it in your shell AND in the env file your cron sources: export ${envVar}=<value>`,
    `verify it resolves: cronfounder doctor`,
    `then resolve this card: (command below)`,
  ];
}

export function setupChannelSteps(channelId: string, driverRef: string | null): string[] {
  const steps = [
    `open channels/${channelId}/setup.md and complete the identity/credential fields (humans own identity — invariant IV)`,
  ];
  if (driverRef) {
    steps.push(
      `add the executable driver mapping under "drivers.${driverRef}" in .cronfounder/config.json (this file is human-owned; see docs/commands.md#drivers)`,
    );
  }
  steps.push(`verify readiness: cronfounder doctor`, `then resolve this card: (command below)`);
  return steps;
}
